#![cfg(test)]
//! End-to-end integration test for the Obol dead-man's-switch.
//!
//! Uses a REAL UltraHonk proof for the Obol liveness circuit (generated by
//! `bb prove` and embedded here). The test:
//!   1. deploys the verifier with the circuit's VK,
//!   2. registers the identity and asserts the ON-CHAIN Merkle root equals the
//!      root the circuit proved against (proving the on-chain Poseidon2 tree is
//!      byte-identical to the off-chain/circuit hashing),
//!   3. verifies a real proof of life via `checkin`,
//!   4. rejects a replayed proof (epoch nullifier already spent),
//!   5. drives the dead-man's-switch: report_missed x3 -> vault activates,
//!   6. lets the sealed beneficiary claim the funds.

use super::*;
use soroban_sdk::{
    testutils::{Address as _, Ledger},
    Address, Bytes, BytesN, Env, String,
};

// Circuit artifacts (built by circuits/liveness before running tests).
const VK: &[u8] = include_bytes!("../../../circuits/liveness/target/vk");
const PROOF: &[u8] = include_bytes!("../../../circuits/liveness/target/proof");
const PUBLIC_INPUTS: &[u8] = include_bytes!("../../../circuits/liveness/target/public_inputs");

fn slice32(env: &Env, src: &[u8], start: usize) -> BytesN<32> {
    let mut a = [0u8; 32];
    a.copy_from_slice(&src[start..start + 32]);
    BytesN::from_array(env, &a)
}

struct World<'a> {
    env: Env,
    registry: LivenessRegistryClient<'a>,
    vault: vault_controller::VaultControllerClient<'a>,
    token: mock_token::MockTokenClient<'a>,
    owner: Address,
}

fn setup<'a>() -> World<'a> {
    let env = Env::default();
    env.mock_all_auths();
    env.ledger().set_timestamp(60); // epoch = 60 / 60 = 1 (matches the proof)

    let owner = Address::generate(&env);
    let fee_collector = Address::generate(&env);

    // Verifier, initialized with the circuit VK.
    let vk = Bytes::from_slice(&env, VK);
    let verifier = env.register(obol_verifier::ObolVerifier, (vk,));

    // Registry wired to the verifier.
    let registry_addr = env.register(LivenessRegistry, (verifier.clone(), owner.clone()));
    let registry = LivenessRegistryClient::new(&env, &registry_addr);

    // Mock token.
    let token_addr = env.register(
        mock_token::MockToken,
        (
            owner.clone(),
            7u32,
            String::from_str(&env, "Mock USD"),
            String::from_str(&env, "mUSD"),
        ),
    );
    let token = mock_token::MockTokenClient::new(&env, &token_addr);

    // Vault controller, wired to the registry (both directions).
    let vault_addr = env.register(
        vault_controller::VaultController,
        (owner.clone(), fee_collector.clone(), 0u32),
    );
    let vault = vault_controller::VaultControllerClient::new(&env, &vault_addr);

    registry.set_vault_controller(&vault_addr);
    vault.set_registry(&registry_addr);

    World {
        env,
        registry,
        vault,
        token,
        owner,
    }
}

#[test]
fn full_lifecycle_register_checkin_activate_claim() {
    let w = setup();
    let env = &w.env;

    // Public inputs = [root | identity_commitment | nullifier_hash | epoch].
    let root = slice32(env, PUBLIC_INPUTS, 0);
    let identity_commitment = slice32(env, PUBLIC_INPUTS, 32);

    // Sealed beneficiary: vault_commitment = SHA-256(recipient_xdr || salt).
    let recipient = Address::generate(env);
    let salt = BytesN::from_array(env, &[9u8; 32]);
    let vault_commitment = w.vault.derive_commitment(&recipient, &salt);

    // Register the identity and link it to the vault (interval = 60s).
    w.registry
        .register(&identity_commitment, &vault_commitment, &60u64);

    // The on-chain Poseidon2 Merkle root MUST equal the circuit's root.
    assert_eq!(w.registry.get_root().unwrap(), root, "on-chain root != circuit root");
    assert_eq!(w.registry.get_member_count(), 1);

    // Fund the vault.
    let depositor = Address::generate(env);
    w.token.mint(&depositor, &1_000i128);
    let blob = Bytes::from_array(env, &[0xAB, 0xCD, 0xEF]);
    w.vault
        .deposit(&depositor, &vault_commitment, &blob, &w.token.address, &1_000i128);
    assert_eq!(w.vault.get_amount(&vault_commitment), 1_000);

    // Proof of life: verify a REAL UltraHonk proof on-chain.
    let public_inputs = Bytes::from_slice(env, PUBLIC_INPUTS);
    let proof = Bytes::from_slice(env, PROOF);
    w.registry.checkin(&public_inputs, &proof);
    assert_eq!(w.registry.get_missed_count(&identity_commitment), 0);

    // Replay must fail: the epoch nullifier is already spent.
    let replay = w.registry.try_checkin(&public_inputs, &proof);
    assert!(replay.is_err(), "replayed proof should be rejected");

    // Dead-man's-switch: owner goes silent. Advance well past the grace window
    // and report three consecutive missed intervals.
    env.ledger().set_timestamp(1_000_000);
    let keeper = Address::generate(env);
    assert_eq!(w.registry.report_missed(&keeper, &identity_commitment), 1);
    assert_eq!(w.registry.report_missed(&keeper, &identity_commitment), 2);
    assert_eq!(w.registry.report_missed(&keeper, &identity_commitment), 3);

    // Threshold reached -> the vault is activated for the beneficiary.
    assert!(w.vault.is_activated(&vault_commitment));

    // The sealed beneficiary reveals the salt and claims.
    w.vault.claim(&vault_commitment, &salt, &recipient);
    assert!(w.vault.is_claimed(&vault_commitment));
    assert_eq!(w.token.balance(&recipient), 1_000);
    assert_eq!(w.vault.get_amount(&vault_commitment), 0);
}

#[test]
fn wrong_beneficiary_cannot_claim() {
    let w = setup();
    let env = &w.env;

    let identity_commitment = slice32(env, PUBLIC_INPUTS, 32);
    let recipient = Address::generate(env);
    let salt = BytesN::from_array(env, &[9u8; 32]);
    let vault_commitment = w.vault.derive_commitment(&recipient, &salt);

    w.registry
        .register(&identity_commitment, &vault_commitment, &60u64);
    let depositor = Address::generate(env);
    w.token.mint(&depositor, &500i128);
    let blob = Bytes::from_array(env, &[0u8; 1]);
    w.vault
        .deposit(&depositor, &vault_commitment, &blob, &w.token.address, &500i128);

    // Force activation directly through the registry path.
    env.ledger().set_timestamp(1_000_000);
    let keeper = Address::generate(env);
    w.registry.report_missed(&keeper, &identity_commitment);
    w.registry.report_missed(&keeper, &identity_commitment);
    w.registry.report_missed(&keeper, &identity_commitment);
    assert!(w.vault.is_activated(&vault_commitment));

    // An attacker with the right salt but a different address cannot claim: the
    // commitment binds the recipient, so the preimage check fails.
    let attacker = Address::generate(env);
    let bad = w.vault.try_claim(&vault_commitment, &salt, &attacker);
    assert!(bad.is_err(), "wrong recipient must not be able to claim");
}

#[test]
fn owner_is_set() {
    let w = setup();
    // Sanity: constructor wired the owner + max_missed default.
    assert_eq!(w.registry.get_max_missed(), 3);
    let _ = &w.owner;
}
